services:
  was-blue:
    image: dlrudgjs104/coinsensor-back:blue-1
    container_name: "coinsensor-back-blue-1"
    build:
      context: ../../
      dockerfile: .github/docker/Dockerfile

  signal-blue:
    image: dlrudgjs104/coinsensor-back:blue-2
    container_name: "coinsensor-back-blue-2"
    build:
      context: ../../
      dockerfile: .github/docker/Dockerfile