services:
  was-green:
    image: dlrudgjs104/coinsensor-back:green-1
    container_name: "coinsensor-back-green-1"
    build:
      context: ../../
      dockerfile: .github/docker/Dockerfile

  signal-green:
    image: dlrudgjs104/coinsensor-back:green-2
    container_name: "coinsensor-back-green-2"
    build:
      context: ../../
      dockerfile: .github/docker/Dockerfile